apiVersion: v2
name: ico-cache
description: Helm chart for ICO-Cache generalized multi-tenant LLM semantic cache
type: application
version: 1.0.0
appVersion: "1.0.4"
maintainers:
  - name: Dev
keywords:
  - llm
  - cache
  - semantic
  - rag
  - vector-db
  - redis
  - qdrant
sources:
  - https://github.com/DEV-S-SHAH/ICO
home: https://github.com/DEV-S-SHAH/ICO