apiVersion: v1
kind: ResourceQuota
metadata:
  name: ico-cache-quota
  namespace: ico-cache
spec:
  hard:
    cpu: "4"
    memory: "8Gi"
    pods: "10"
    services: "5"
    persistentvolumeclaims: "4"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"