import { Command } from 'commander';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { detectProject } from '../utils/project-detection.js';
import { readFileSafe, writeFileSafe, fileExists } from '../utils/file-utils.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ConnectOptions {
  provider?: string;
  model?: string;
  baseUrl?: string;
  apiKey?: string;
  gatewayUrl?: string;
  yes?: boolean;
}

const OPENAI_COMPATIBLE_PROVIDERS = [
  { name: 'OpenAI', value: 'openai', envVar: 'OPENAI_API_KEY', defaultModel: 'gpt-4o-mini', defaultBaseUrl: 'https://api.openai.com/v1' },
  { name: 'Anthropic (via LiteLLM)', value: 'anthropic', envVar: 'ANTHROPIC_API_KEY', defaultModel: 'claude-3-5-sonnet-20241022', defaultBaseUrl: 'https://api.anthropic.com' },
  { name: 'Google Gemini (via LiteLLM)', value: 'gemini', envVar: 'GEMINI_API_KEY', defaultModel: 'gemini/gemini-flash-latest', defaultBaseUrl: 'https://generativelanguage.googleapis.com' },
  { name: 'Ollama (local)', value: 'ollama', envVar: 'OLLAMA_BASE_URL', defaultModel: 'llama3.1', defaultBaseUrl: 'http://localhost:11434/v1' },
  { name: 'Custom OpenAI-compatible', value: 'custom', envVar: 'CUSTOM_API_KEY', defaultModel: 'custom', defaultBaseUrl: '' },
];

async function loadEnvFile(envPath: string): Promise<Record<string, string>> {
  const content = await readFileSafe(envPath);
  if (!content) return {};
  
  const env: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      const key = trimmed.slice(0, eqIndex).trim();
      const value = trimmed.slice(eqIndex + 1).trim();
      env[key] = value;
    }
  }
  return env;
}

function generateOpenAIProxyCode(gatewayUrl: string, apiKey: string, projectType: string): string {
  if (projectType === 'python') {
    return `#!/usr/bin/env python
"""
OpenAI-Compatible Proxy for ICO-Cache
Generated by \`ico-cache connect\`

This creates an OpenAI-compatible endpoint that routes through ICO-Cache.
Replace your OpenAI base_url with: ${gatewayUrl}/v1/openai
"""

import os
from openai import AsyncOpenAI

# Configure OpenAI client to use ICO-Cache gateway
client = AsyncOpenAI(
    api_key="${apiKey}",
    base_url="${gatewayUrl}/v1/openai",
)

async def main():
    # Example: Use exactly like OpenAI API
    response = await client.chat.completions.create(
        model="gpt-4o-mini",  # This maps to your configured model in ICO-Cache
        messages=[
            {"role": "user", "content": "What is the capital of France?"}
        ],
    )
    print(response.choices[0].message.content)

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
`;
  }
  
  return `/**
 * OpenAI-Compatible Proxy for ICO-Cache
 * Generated by \`ico-cache connect\`
 * 
 * This creates an OpenAI-compatible endpoint that routes through ICO-Cache.
 * Replace your OpenAI base_url with: ${gatewayUrl}/v1/openai
 */

import OpenAI from 'openai';

// Configure OpenAI client to use ICO-Cache gateway
const client = new OpenAI({
  apiKey: '${apiKey}',
  baseURL: '${gatewayUrl}/v1/openai',
});

async function main() {
  // Example: Use exactly like OpenAI API
  const response = await client.chat.completions.create({
    model: 'gpt-4o-mini',  // This maps to your configured model in ICO-Cache
    messages: [
      { role: 'user', content: 'What is the capital of France?' }
    ],
  });
  console.log(response.choices[0].message.content);
}

main().catch(console.error);
`;
}

function generatePythonMiddlewareCode(gatewayUrl: string, apiKey: string): string {
  return `#!/usr/bin/env python
"""
ICO-Cache Middleware for OpenAI-Compatible Clients
Generated by \`ico-cache connect\`

Use this as a drop-in replacement for your OpenAI client.
"""

import os
import httpx
from typing import Any, Dict, List, Optional
from openai import AsyncOpenAI, OpenAI

class IcoCacheOpenAIClient:
    """OpenAI-compatible client that routes through ICO-Cache."""
    
    def __init__(
        self,
        api_key: str = "${apiKey}",
        base_url: str = "${gatewayUrl}/v1/openai",
        **kwargs
    ):
        self.client = AsyncOpenAI(
            api_key=api_key,
            base_url=base_url,
            **kwargs
        )
        self.sync_client = OpenAI(
            api_key=api_key,
            base_url=base_url,
            **kwargs
        )
    
    # Async methods (delegate to async client)
    @property
    def chat(self):
        return self.client.chat
    
    @property
    def completions(self):
        return self.client.completions
    
    @property
    def embeddings(self):
        return self.client.embeddings
    
    @property
    def models(self):
        return self.client.models
    
    # Sync methods (delegate to sync client)
    @property
    def chat_sync(self):
        return self.sync_client.chat
    
    @property
    def completions_sync(self):
        return self.sync_client.completions


# Drop-in replacement for OpenAI client
def create_client(**kwargs) -> IcoCacheOpenAIClient:
    """Create an ICO-Cache OpenAI client."""
    return IcoCacheOpenAIClient(**kwargs)


# Example usage
async def main():
    client = create_client()
    
    # Use exactly like OpenAI
    response = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": "Hello, ICO-Cache!"}],
    )
    print(response.choices[0].message.content)

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
`;
}

function generateNodeMiddlewareCode(gatewayUrl: string, apiKey: string): string {
  return `/**
 * ICO-Cache Middleware for OpenAI-Compatible Clients
 * Generated by \`ico-cache connect\`
 * 
 * Use this as a drop-in replacement for your OpenAI client.
 */

import OpenAI from 'openai';

class IcoCacheOpenAIClient {
  constructor(options = {}) {
    this.client = new OpenAI({
      apiKey: options.apiKey || '${apiKey}',
      baseURL: options.baseURL || '${gatewayUrl}/v1/openai',
      ...options,
    });
  }

  // Delegate all OpenAI methods
  get chat() { return this.client.chat; }
  get completions() { return this.client.completions; }
  get embeddings() { return this.client.embeddings; }
  get models() { return this.client.models; }
  get beta() { return this.client.beta; }
  get files() { return this.client.files; }
  get fineTuning() { return this.client.fineTuning; }
  get images() { return this.client.images; }
  get audio() { return this.client.audio; }
  get moderations() { return this.client.moderations; }
  get vectorStores() { return this.client.vectorStores; }
}

// Drop-in replacement for OpenAI client
export function createClient(options = {}) {
  return new IcoCacheOpenAIClient(options);
}

export default IcoCacheOpenAIClient;

// Example usage
async function main() {
  const client = createClient();
  
  // Use exactly like OpenAI
  const response = await client.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [{ role: 'user', content: 'Hello, ICO-Cache!' }],
  });
  console.log(response.choices[0].message.content);
}

main().catch(console.error);
`;
}

export const connectCommand = new Command('connect')
  .description('Connect an existing OpenAI-compatible application to ICO-Cache')
  .option('-p, --provider <provider>', 'LLM provider (openai, anthropic, gemini, ollama, custom)')
  .option('-m, --model <model>', 'Model name')
  .option('--base-url <url>', 'Provider base URL')
  .option('-k, --api-key <key>', 'API key for the provider')
  .option('-g, --gateway-url <url>', 'ICO-Cache gateway URL', 'http://localhost:8000')
  .option('-y, --yes', 'Skip prompts and use defaults')
  .action(async (options: ConnectOptions) => {
    console.log(chalk.bold('\n🔌 Connecting OpenAI-compatible app to ICO-Cache...\n'));

    const projectInfo = await detectProject();
    
    // Load existing .env if available
    const env = await loadEnvFile('.env');
    
    // Determine provider
    let providerInfo = OPENAI_COMPATIBLE_PROVIDERS.find(p => p.value === options.provider);
    
    if (!providerInfo && !options.yes) {
      const { provider } = await inquirer.prompt([
        {
          type: 'list',
          name: 'provider',
          message: 'Select your LLM provider:',
          choices: OPENAI_COMPATIBLE_PROVIDERS.map(p => ({
            name: p.name,
            value: p.value,
          })),
          default: 'openai',
        },
      ]);
      providerInfo = OPENAI_COMPATIBLE_PROVIDERS.find(p => p.value === provider)!;
    } else if (!providerInfo) {
      providerInfo = OPENAI_COMPATIBLE_PROVIDERS[0]; // Default to OpenAI
    }

    // Get model
    let model = options.model || env.LLM_MODEL || providerInfo.defaultModel;
    if (!options.model && !options.yes) {
      const { selectedModel } = await inquirer.prompt([
        {
          type: 'input',
          name: 'selectedModel',
          message: `Model name:`,
          default: model,
        },
      ]);
      model = selectedModel;
    }

    // Get base URL
    let baseUrl = options.baseUrl || env.LLM_BASE_URL || providerInfo.defaultBaseUrl;
    if (providerInfo.value === 'custom' && !options.baseUrl && !options.yes) {
      const { customUrl } = await inquirer.prompt([
        {
          type: 'input',
          name: 'customUrl',
          message: 'Custom API base URL:',
          default: baseUrl,
        },
      ]);
      baseUrl = customUrl;
    }

    // Get API key
    let apiKey = options.apiKey || env[providerInfo.envVar] || env.API_KEY || '';
    if (!apiKey && !options.yes) {
      const { key } = await inquirer.prompt([
        {
          type: 'password',
          name: 'key',
          message: `API key (${providerInfo.envVar}):`,
          mask: '*',
        },
      ]);
      apiKey = key;
    }

    // Get gateway URL
    let gatewayUrl = options.gatewayUrl || env.GATEWAY_URL || 'http://localhost:8000';
    if (!options.gatewayUrl && !options.yes) {
      const { url } = await inquirer.prompt([
        {
          type: 'input',
          name: 'url',
          message: 'ICO-Cache gateway URL:',
          default: gatewayUrl,
        },
      ]);
      gatewayUrl = url;
    }

    // Generate gateway API key for the app
    const crypto = await import('crypto');
    const gatewayApiKey = crypto.randomBytes(32).toString('hex');

    console.log(chalk.green('\n✅ Configuration complete!'));
    console.log(chalk.gray('\nGenerated integration files:'));

    // Generate integration files
    const proxyCode = generateOpenAIProxyCode(gatewayUrl, gatewayApiKey, projectInfo.type);
    const proxyFile = projectInfo.type === 'python' ? 'openai_proxy.py' : 'openai_proxy.js';
    
    await writeFileSafe(proxyFile, proxyCode);
    console.log(chalk.gray(`  ${proxyFile} - OpenAI-compatible proxy client`));

    // Generate middleware wrapper
    const middlewareCode = projectInfo.type === 'python' 
      ? generatePythonMiddlewareCode(gatewayUrl, gatewayApiKey)
      : generateNodeMiddlewareCode(gatewayUrl, gatewayApiKey);
    const middlewareFile = projectInfo.type === 'python' ? 'ico_cache_openai.py' : 'ico_cache_openai.js';
    
    await writeFileSafe(middlewareFile, middlewareCode);
    console.log(chalk.gray(`  ${middlewareFile} - Drop-in OpenAI client wrapper`));

    // Update .env.example with gateway key
    const envExamplePath = '.env.example';
    if (await fileExists(envExamplePath)) {
      let envContent = await readFileSafe(envExamplePath) || '';
      
      // Add or update API_KEYS
      const apiKeysLine = `API_KEYS={"${gatewayApiKey}": "default"}`;
      if (envContent.includes('API_KEYS=')) {
        envContent = envContent.replace(/API_KEYS=.*/, apiKeysLine);
      } else {
        envContent += `\n\n# ICO-Cache Gateway API Key (generated by \`ico-cache connect\`)\n${apiKeysLine}\n`;
      }
      
      await writeFileSafe(envExamplePath, envContent);
      console.log(chalk.gray(`  ${envExamplePath} - Updated with gateway API key`));
    }

    // Summary
    console.log(chalk.bold('\n📋 Next steps:'));
    console.log(chalk.gray('  1. Copy .env.example to .env (if not already done):'));
    console.log(chalk.cyan('     cp .env.example .env'));
    console.log(chalk.gray('  2. Ensure your ICO-Cache gateway is running:'));
    console.log(chalk.cyan('     ico-cache start'));
    console.log(chalk.gray('  3. In your existing application, replace:'));
    console.log(chalk.gray('     - OpenAI base_url: https://api.openai.com/v1'));
    console.log(chalk.green(`     + OpenAI base_url: ${gatewayUrl}/v1/openai`));
    console.log(chalk.gray('     - API key: your-openai-key'));
    console.log(chalk.green(`     + API key: ${gatewayApiKey}`));
    console.log(chalk.gray('  4. Or use the generated wrapper:'));
    if (projectInfo.type === 'python') {
      console.log(chalk.cyan('     from ico_cache_openai import create_client'));
      console.log(chalk.cyan('     client = create_client()'));
    } else {
      console.log(chalk.cyan('     import { createClient } from "./ico_cache_openai.js"'));
      console.log(chalk.cyan('     const client = createClient();'));
    }

    console.log(chalk.bold('\n🎯 Your app now uses ICO-Cache for semantic caching!'));
    console.log(chalk.gray('   - L1 Exact Match: Instant cache hits for identical prompts'));
    console.log(chalk.gray('   - L2 Semantic: Cache hits for semantically similar prompts'));
    console.log(chalk.gray('   - L3 Context-Aware: Cache hits with context awareness'));
  });