apiVersion: v1
kind: LimitRange
metadata:
  name: ico-cache-dev-limits
  namespace: ico-cache-dev
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "1"
        memory: "2Gi"
      min:
        cpu: "10m"
        memory: "32Mi"
      maxLimitRequestRatio:
        cpu: "20"
        memory: "20"